# CHANGEME


acendTraining:
  servicePort: 8080
  deployments:
    - 
      name: acend
      replicaCount: 1
      image:
        repository: quay.io/acend/cilium-basics-training
        pullPolicy: Always
        tag: ""
        tagsuffix: ""
      ingress:
        annotations: 
          kubernetes.io/ingress.class: nginx-public
        secretOverride: acend-wildcard
        appname: cilium-basics
        domain: training.acend.ch
    - 
      name: puzzle
      replicaCount: 1
      image:
        repository: quay.io/acend/cilium-basics-training
        pullPolicy: Always
        tag: ""
        tagsuffix: "-puzzle"
      ingress:
        annotations: 
          kubernetes.io/ingress.class: nginx-public
        useDefaultSecret: true
        appname: cilium-basics-training
        domain: k8s.puzzle.ch
    - 
      name: techlab
      replicaCount: 1
      image:
        repository: quay.io/acend/cilium-techlab
        pullPolicy: Always
        tag: ""
        tagsuffix: ""
      ingress:
        annotations: 
          kubernetes.io/ingress.class: nginx-public
        secretOverride: acend-wildcard
        appname: cilium-techlab
        domain: training.acend.ch



nameOverride: "cilium-basics-training"
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""